version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: archiver
    versions:
    - 5.2.0
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: gulp-mocha
    versions:
    - 7.0.2
